CREATE TABLE applications(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name TEXT NOT NULL,
    salary NUMERIC(15, 2) NOT NULL,
    credit_amount NUMERIC(15, 2) NOT NULL,
    status VARCHAR(20) NOT NULL,
    credit_purpose TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    version INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX idx_applications_status ON applications(status);
CREATE INDEX idx_applications_full_name ON applications(full_name);
CREATE INDEX idx_applications_created_at ON applications(created_at);